name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  CC: /usr/bin/gcc
  CXX: /usr/bin/g++

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-24.04
    env:
      SONAR_SCANNER_VERSION: 4.7.0.2747 # Find the latest version in the "Linux" link on this page:
                                        # https://docs.sonarcloud.io/advanced-setup/ci-based-analysis/sonarscanner-cli/
      SONAR_SERVER_URL: "https://sonarcloud.io"
      BUILD_WRAPPER_OUT_DIR: build_wrapper_output_directory # Directory where build-wrapper output will be placed
    steps:
      - uses: actions/checkout@v3
        with:
         fetch-depth: 0

      - name: update container base
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt-get -qq update -y
          sudo apt-get -qq install -y git sudo pkg-config ccache python3-pip libluajit-5.1-2 luajit luajit-5.1-dev libcrypto++8t64 libcrypto++-dev liburing-dev doxygen

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-seastar

      - name: add ccache to path
        run: |
          echo "/usr/lib/ccache" >> $GITHUB_PATH
          echo "/usr/local/opt/ccache/libexec" >> $GITHUB_PATH
      
      - uses: actions/checkout@master
        with:
          repository: scylladb/seastar
          path: seastar
          ref: seastar-25.05.0

      - name: install dependencies
        run: |
          cd seastar
          sudo ./install-dependencies.sh
          ./configure.py --mode=release --prefix=/usr/local --without-tests --without-apps --without-demos --ccache
          ninja -C build/release -j$(nproc)
          sudo ninja -C build/release install
 
      - name: Install Conan
        run: |
          python -m pip install --break-system-packages conan -v "conan>=2.0"
          conan profile detect --force

      - name: Install dependencies with Conan
        run: |
          conan install . --output-folder=build --build=missing -s compiler.cppstd=23 -s build_type=${{ env.BUILD_TYPE }}
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Download and set up sonar-scanner
        env:
          SONAR_SCANNER_DOWNLOAD_URL: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-${{ env.SONAR_SCANNER_VERSION }}-linux.zip
        run: |
          mkdir -p $HOME/.sonar
          curl -sSL -C - -o $HOME/.sonar/sonar-scanner.zip ${{ env.SONAR_SCANNER_DOWNLOAD_URL }} 
          unzip -o $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}-linux/bin" >> $GITHUB_PATH
      - name: Download and set up build-wrapper
        env:
          BUILD_WRAPPER_DOWNLOAD_URL: ${{ env.SONAR_SERVER_URL }}/static/cpp/build-wrapper-linux-x86.zip
        run: |
          curl -sSL -C - -o $HOME/.sonar/build-wrapper-linux-x86.zip ${{ env.BUILD_WRAPPER_DOWNLOAD_URL }}
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar/
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH

      - name: Run build-wrapper
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS=--coverage -DCMAKE_C_FLAGS=--coverage -DCMAKE_CXX_STANDARD=23 -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -DWARNINGS_AS_ERRORS=OFF
          build-wrapper-linux-x86-64 --out-dir ${{ env.BUILD_WRAPPER_OUT_DIR }} cmake --build build/ --config Debug

      - name: Test
        working-directory: '${{ github.workspace }}/build'
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest --output-on-failure
        
      - name: SonarQube
        working-directory: '${{ github.workspace }}/build'
        run: |        
          sudo pip install --break-system-packages gcovr cpp-coveralls
          gcovr -r .. --gcov-ignore-parse-errors=negative_hits.warn --sonarqube coverage.xml
          mv coverage.xml ..

      - name: Upload coverage report
        working-directory: ${{github.workspace}}
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          export COVERALLS_SERVICE_NAME="github-workflows"
          coveralls -E ".*/build/.*.c((pp)|(c)|(xx))?$" -e test -e seastar -e fuzz_test -e cmake -e eve -e luajit -e sol2 --gcov /usr/bin/gcov --gcov-options '\-lp' > /dev/null